// flow-typed signature: b6edc472946e6b3c04335f474b888f61
// flow-typed version: <<STUB>>/exit-hook_v1.1.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exit-hook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exit-hook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exit-hook/index' {
  declare module.exports: $Exports<'exit-hook'>;
}
declare module 'exit-hook/index.js' {
  declare module.exports: $Exports<'exit-hook'>;
}
