// flow-typed signature: 0f051a48da9b680ab6791b6ba16c36a6
// flow-typed version: <<STUB>>/ping_v0.2.2/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ping'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ping' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ping/examples/example' {
  declare module.exports: any;
}

declare module 'ping/examples/example2' {
  declare module.exports: any;
}

declare module 'ping/Gruntfile' {
  declare module.exports: any;
}

declare module 'ping/lib/builder/factory' {
  declare module.exports: any;
}

declare module 'ping/lib/builder/linux' {
  declare module.exports: any;
}

declare module 'ping/lib/builder/mac' {
  declare module.exports: any;
}

declare module 'ping/lib/builder/win' {
  declare module.exports: any;
}

declare module 'ping/lib/parser/base' {
  declare module.exports: any;
}

declare module 'ping/lib/parser/factory' {
  declare module.exports: any;
}

declare module 'ping/lib/parser/linux' {
  declare module.exports: any;
}

declare module 'ping/lib/parser/mac' {
  declare module.exports: any;
}

declare module 'ping/lib/parser/win' {
  declare module.exports: any;
}

declare module 'ping/lib/ping-pcap' {
  declare module.exports: any;
}

declare module 'ping/lib/ping-promise' {
  declare module.exports: any;
}

declare module 'ping/lib/ping-sys' {
  declare module.exports: any;
}

declare module 'ping/test/load-fixture-path' {
  declare module.exports: any;
}

declare module 'ping/test/test-ping' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ping/examples/example.js' {
  declare module.exports: $Exports<'ping/examples/example'>;
}
declare module 'ping/examples/example2.js' {
  declare module.exports: $Exports<'ping/examples/example2'>;
}
declare module 'ping/Gruntfile.js' {
  declare module.exports: $Exports<'ping/Gruntfile'>;
}
declare module 'ping/index' {
  declare module.exports: $Exports<'ping'>;
}
declare module 'ping/index.js' {
  declare module.exports: $Exports<'ping'>;
}
declare module 'ping/lib/builder/factory.js' {
  declare module.exports: $Exports<'ping/lib/builder/factory'>;
}
declare module 'ping/lib/builder/linux.js' {
  declare module.exports: $Exports<'ping/lib/builder/linux'>;
}
declare module 'ping/lib/builder/mac.js' {
  declare module.exports: $Exports<'ping/lib/builder/mac'>;
}
declare module 'ping/lib/builder/win.js' {
  declare module.exports: $Exports<'ping/lib/builder/win'>;
}
declare module 'ping/lib/parser/base.js' {
  declare module.exports: $Exports<'ping/lib/parser/base'>;
}
declare module 'ping/lib/parser/factory.js' {
  declare module.exports: $Exports<'ping/lib/parser/factory'>;
}
declare module 'ping/lib/parser/linux.js' {
  declare module.exports: $Exports<'ping/lib/parser/linux'>;
}
declare module 'ping/lib/parser/mac.js' {
  declare module.exports: $Exports<'ping/lib/parser/mac'>;
}
declare module 'ping/lib/parser/win.js' {
  declare module.exports: $Exports<'ping/lib/parser/win'>;
}
declare module 'ping/lib/ping-pcap.js' {
  declare module.exports: $Exports<'ping/lib/ping-pcap'>;
}
declare module 'ping/lib/ping-promise.js' {
  declare module.exports: $Exports<'ping/lib/ping-promise'>;
}
declare module 'ping/lib/ping-sys.js' {
  declare module.exports: $Exports<'ping/lib/ping-sys'>;
}
declare module 'ping/test/load-fixture-path.js' {
  declare module.exports: $Exports<'ping/test/load-fixture-path'>;
}
declare module 'ping/test/test-ping.js' {
  declare module.exports: $Exports<'ping/test/test-ping'>;
}
